/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js type tooling. Keep it committed so a fresh
// checkout can type-check before `next dev` has run locally.
